/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/etiennecoutaud/kanary/pkg/apis/kanary/v1"
	scheme "github.com/etiennecoutaud/kanary/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KanariesGetter has a method to return a KanaryInterface.
// A group's client should implement this interface.
type KanariesGetter interface {
	Kanaries(namespace string) KanaryInterface
}

// KanaryInterface has methods to work with Kanary resources.
type KanaryInterface interface {
	Create(*v1.Kanary) (*v1.Kanary, error)
	Update(*v1.Kanary) (*v1.Kanary, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.Kanary, error)
	List(opts meta_v1.ListOptions) (*v1.KanaryList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Kanary, err error)
	KanaryExpansion
}

// kanaries implements KanaryInterface
type kanaries struct {
	client rest.Interface
	ns     string
}

// newKanaries returns a Kanaries
func newKanaries(c *KanaryV1Client, namespace string) *kanaries {
	return &kanaries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kanary, and returns the corresponding kanary object, and an error if there is any.
func (c *kanaries) Get(name string, options meta_v1.GetOptions) (result *v1.Kanary, err error) {
	result = &v1.Kanary{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kanaries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kanaries that match those selectors.
func (c *kanaries) List(opts meta_v1.ListOptions) (result *v1.KanaryList, err error) {
	result = &v1.KanaryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kanaries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kanaries.
func (c *kanaries) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kanaries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kanary and creates it.  Returns the server's representation of the kanary, and an error, if there is any.
func (c *kanaries) Create(kanary *v1.Kanary) (result *v1.Kanary, err error) {
	result = &v1.Kanary{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kanaries").
		Body(kanary).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kanary and updates it. Returns the server's representation of the kanary, and an error, if there is any.
func (c *kanaries) Update(kanary *v1.Kanary) (result *v1.Kanary, err error) {
	result = &v1.Kanary{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kanaries").
		Name(kanary.Name).
		Body(kanary).
		Do().
		Into(result)
	return
}

// Delete takes name of the kanary and deletes it. Returns an error if one occurs.
func (c *kanaries) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kanaries").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kanaries) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kanaries").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kanary.
func (c *kanaries) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Kanary, err error) {
	result = &v1.Kanary{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kanaries").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
