---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-v1
  labels:
    k8s-app: app-v1
  namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http
    interval: 5s
  selector:
    matchLabels:
      k8s-app: app-v1
  namespaceSelector:
    matchNames:
    - kanary
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-v2
  labels:
    k8s-app: app-v2
  namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http
    interval: 5s
  selector:
    matchLabels:
      k8s-app: app-v2
  namespaceSelector:
    matchNames:
    - kanary
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: injector
  labels:
    k8s-app: injector
  namespace: monitoring
spec:
  jobLabel: k8s-app
  endpoints:
  - port: http
    interval: 5s
  selector:
    matchLabels:
      k8s-app: injector
  namespaceSelector:
    matchNames:
    - kanary
