/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kanary_v1 "github.com/etiennecoutaud/kanary/pkg/apis/kanary/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKanaries implements KanaryInterface
type FakeKanaries struct {
	Fake *FakeKanaryV1
	ns   string
}

var kanariesResource = schema.GroupVersionResource{Group: "kanary.io", Version: "v1", Resource: "kanaries"}

var kanariesKind = schema.GroupVersionKind{Group: "kanary.io", Version: "v1", Kind: "Kanary"}

// Get takes name of the kanary, and returns the corresponding kanary object, and an error if there is any.
func (c *FakeKanaries) Get(name string, options v1.GetOptions) (result *kanary_v1.Kanary, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kanariesResource, c.ns, name), &kanary_v1.Kanary{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kanary_v1.Kanary), err
}

// List takes label and field selectors, and returns the list of Kanaries that match those selectors.
func (c *FakeKanaries) List(opts v1.ListOptions) (result *kanary_v1.KanaryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kanariesResource, kanariesKind, c.ns, opts), &kanary_v1.KanaryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kanary_v1.KanaryList{}
	for _, item := range obj.(*kanary_v1.KanaryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kanaries.
func (c *FakeKanaries) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kanariesResource, c.ns, opts))

}

// Create takes the representation of a kanary and creates it.  Returns the server's representation of the kanary, and an error, if there is any.
func (c *FakeKanaries) Create(kanary *kanary_v1.Kanary) (result *kanary_v1.Kanary, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kanariesResource, c.ns, kanary), &kanary_v1.Kanary{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kanary_v1.Kanary), err
}

// Update takes the representation of a kanary and updates it. Returns the server's representation of the kanary, and an error, if there is any.
func (c *FakeKanaries) Update(kanary *kanary_v1.Kanary) (result *kanary_v1.Kanary, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kanariesResource, c.ns, kanary), &kanary_v1.Kanary{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kanary_v1.Kanary), err
}

// Delete takes name of the kanary and deletes it. Returns an error if one occurs.
func (c *FakeKanaries) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kanariesResource, c.ns, name), &kanary_v1.Kanary{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKanaries) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kanariesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &kanary_v1.KanaryList{})
	return err
}

// Patch applies the patch and returns the patched kanary.
func (c *FakeKanaries) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *kanary_v1.Kanary, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kanariesResource, c.ns, name, data, subresources...), &kanary_v1.Kanary{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kanary_v1.Kanary), err
}
